SQUARE_SIZE = 20
BOARD_HEIGHT = 25
BOARD_WIDTH = 50
CREDENTIAL_OFFSET = 2
UI_ELEMENT_HEIGHT = 60
BUTTON_WIDTH = 500
EMPTY_CELL_STYLE = "background:white; border: 1px solid #3342a1; border-radius: 1px; margin: 0.5px;"
FULL_CELL_STYLE = "background:#150b45; border: 1px solid #3342a1; border-radius: 1px; margin: 0.5px;"
TITLE_TEXT_STYLE = "font-size:36px;font-weight:bold;font-style:oblique;"
AUTHOR_TEXT_STYLE = "font-size: 24px;font-weight: lighter; font-style: oblique;"
BOTTOM_LABEL_TEXT_STYLE = "font-size: 16px;font-weight: bold; font-style: oblique; text-align:right;"
ERROR_LABEL_TEXT_STYLE = "font-size: 14px;font-weight: bold;  text-align:right; color:red;"
INFO_LABEL_TEXT_STYLE = "font-size: 14px; font-weight: lighter;font-style: oblique; text-align:right; color:150b45;"
GAME_NAME = "Gra w zycie"
AUTHOR = "Daniel Załęski"
MAX_STARTING_POPULATION_COUNT_PER_ROW = 30
